; HD715.ASM

; This file tests header file usage for the specified processor.

	LIST	P=16C715
	INCLUDE	"p16c715.inc"

 	DATA	_CP_ALL, 0x00CF		; This changes per device
	DATA	_CP_50, 0X15DF
	DATA	_CP_OFF, 0X3FFF
	DATA	_BODEN_ON, 0X3FFF
	DATA	_BODEN_OFF, 0X3FBF
	DATA	_PWRTE_ON, 0x3FF7	; This changes per device
	DATA	_PWRTE_OFF, 0X3FFF
	DATA	_WDT_ON, 0X3FFF
	DATA	_WDT_OFF, 0X3FFB
	DATA	_LP_OSC, 0X3FFC
	DATA	_XT_OSC, 0X3FFD
	DATA	_HS_OSC, 0X3FFE
	DATA	_RC_OSC, 0X3FFF


	DATA	INDF, 0			;Register Files
	DATA	TMR0, 1
	DATA	PCL, 2
	DATA	STATUS, 3
	DATA	FSR, 4
	DATA	PORTA, 5
	DATA	PORTB, 6
	DATA	PCLATH, 0x0A
	DATA	INTCON, 0x0B
	DATA	PIR1, 0XC		; Register Files
	DATA	ADRES, 0x1E		; ADC_CONFIG 1 Reg. Files
	DATA	ADCON0, 0X1F

	DATA	OPTION_REG, 0x81
	DATA	TRISA, 0X85
	DATA	TRISB, 0X86
	DATA	PIE1, 0X8C
	DATA	PCON, 0X8E
	DATA	ADCON1, 0X9F


	DATA	ADCS1, 7		; ADCON0
	DATA	ADCS0, 6
	DATA	CHS2, 5
	DATA	CHS1, 4
	DATA	CHS0, 3
	DATA	GO, 2
	DATA	NOT_DONE, 2
	DATA	GO_DONE, 2
	DATA	ADON, 0

	DATA	PCFG1, 1		; ADCON1
	DATA	PCFG0, 0

	DATA	ADIE, 6			; PIE1 and PIR1
	DATA	ADIF, 6	
	
	DATA	NOT_MPE, 2 
	DATA	NOT_POR, 1		; PCON
	DATA	NOT_BO, 0

	DATA	GIE, 7			; INTCON
	DATA	PEIE, 6			; Finish INTCON Definition
	DATA	T0IE, 5
	DATA	INTE, 4
	DATA	RBIE, 3
	DATA	T0IF, 2
	DATA	INTF, 1
	DATA	RBIF, 0	

	DATA	NOT_RBPU, 7		; OPTION
	DATA	INTEDG, 6
	DATA	T0CS, 5
	DATA	T0SE, 4
	DATA	PSA, 3
	DATA	PS2, 2
	DATA	PS1, 1
	DATA	PS0, 0


	DATA	IRP, 7			;STATUS
	DATA	RP1, 6
	DATA	RP0, 5
	DATA	NOT_TO, 4
	DATA	NOT_PD, 3
	DATA	Z, 2
	DATA	DC, 1
	DATA	C, 0

	END
