#!/bin/bash

# generate Makefile.am from the directory contents

echo "## This file was automatically generated by Makefile.sh" > Makefile.am
echo >> Makefile.am
echo "pkgdatadir = @GPUTILS_HEADER_PATH@" >> Makefile.am
echo >> Makefile.am
echo "EXTRA_DIST =\\" >> Makefile.am

# count the number of items in the list
let count=0
for x in `ls *.inc | sort`
  do
    let count=count+1
  done

# output the file list
let pass=0
for x in `ls *.inc | sort`
  do
    let pass=pass+1
    if [ $pass -eq $count ]; then
      echo "	$x" >> Makefile.am
    else
      echo "	$x \\" >> Makefile.am
    fi
  done
 
echo >> Makefile.am
echo "pkgdata_DATA = \$(EXTRA_DIST)" >> Makefile.am
echo >> Makefile.am
echo "noinst_PROGRAMS = header_check" >> Makefile.am
echo >> Makefile.am
echo "AM_CPPFLAGS = -I\${top_srcdir}/include" >> Makefile.am
echo >> Makefile.am
echo "header_check_SOURCES = header_check.c" >> Makefile.am
echo >> Makefile.am
echo "check:" >> Makefile.am
echo "	list='\$(EXTRA_DIST)'; for file in \$\$list; do \\" >> Makefile.am
echo "	  echo "Testing \$\$file"; ./header_check \$\$file; \\" >> Makefile.am
echo "	done;" >> Makefile.am

echo "Please run \"make check\""
